version: '3.8'

services:
        python:
                build: .
                container_name: fairness
                ports:
                        - "8888:8888"
                        - "7777:7777"
                volumes:
                        - type: bind
                          source: .
                          target: /home/jovyan/work

                working_dir: /home/jovyan/work
